# Gorseの基本的な設定ファイル

[server]
default_n = 10
api_key = ""

[recommend.data_source]
positive_feedback_types = ["purchase", "like"]
read_feedback_types = ["view"]

[recommend.popular]
popular_window = "720h"

[recommend.collaborative]
model_fit_period = "60m"  # モデルを訓練する間隔

[recommend.offline]
check_recommend_period = "30m"
refresh_recommend_period = "60m"
enable_latest_recommend = true
enable_popular_recommend = true
enable_user_based_recommend = true
enable_item_based_recommend = true
enable_collaborative_recommend = true

[master]
port = 8086
host = "0.0.0.0"
dashboard_port = 8088

[log]
level = "info"
